
services:
  broker:
    build: ./data_broker
    ports: 
      - "3000:3000"

  simulator-a:
    build: ./eeg_acquisition
    environment:
      ACQ_PORT: ${ACQ_PORT_A}
      PACKET_INTERVAL: ${PACKET_INTERVAL_A}
    command: python simulator.py
    ports: 
      - "13854:13854"

  simulator-b:
    build: ./eeg_acquisition
    environment:
      ACQ_PORT: ${ACQ_PORT_B}
      PACKET_INTERVAL: ${PACKET_INTERVAL_B}
    command: python simulator.py
    ports:
      - "13855:13855"

  acquisition-a:
    build: ./eeg_acquisition
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PLAYER_ID: ${PLAYER_ID_A}
      ACQ_PORT: ${ACQ_PORT_A}
      BROKER_URL: ${BROKER_URL}
      POOR_SIGNAL_LEVEL_THRESHOLD: ${POOR_SIGNAL_LEVEL_THRESHOLD}
      EEG_HOST: ${EEG_HOST_A}
    command: python acquisition_service.py
    depends_on: 
      - broker
      - simulator-a

  acquisition-b:
    build: ./eeg_acquisition
    environment:
      PLAYER_ID: ${PLAYER_ID_B}
      ACQ_PORT: ${ACQ_PORT_B}
      BROKER_URL: ${BROKER_URL}
      POOR_SIGNAL_LEVEL_THRESHOLD: ${POOR_SIGNAL_LEVEL_THRESHOLD}
      EEG_HOST: ${EEG_HOST_B}
    command: python acquisition_service.py
    depends_on: 
      - broker
      - simulator-b
  
  test-client:
    build: ./test_client
    environment:
      BROKER_URL: "http://broker:3000"
    depends_on:
      - broker

  # dashboard:
  #   build: ./dashboard

  #   ports:
  #     - "8000:80"

  #   depends_on:
  #     - broker

  # collector_service:
  #   build: ./metrics_collector/collector_service
  #   environment:
  #     BROKER_URL: "http://broker:3000"
  #   volumes:
  #     - ./metrics_collector/results:/results
  #   command: python collector_service.py
  #   depends_on:
  #     - broker
  # analysis_service:
  #   build: ./metrics_collector/analysis_service
  #   environment:
  #     BROKER_URL: "http://broker:3000"
  #   volumes:
  #     - ./metrics_collector/results:/results
  #   depends_on:
  #     - broker
  #     - collector_service

# volumes:
#   db_data:

